---
title: "Noter om stratificeret sampling"
author: "PSL"
date: "September 27, 2018"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Kort resumé af SRS og HT-estimatoren
Antag at vi har en population med $N$ enheder, og at enhederne har en egenskab $y$. Vi ønsker at bestemme den totale sum af denne egenskab i hele populationen:
$$ t_y = \sum _{j=1}^N y_j$$
Til dette formål udtager vi en stikprøve af størrelsen $n$ ved simpel udvælgelse (SRS, simple random sample) hvorved sandsynligheden for udvælgelse $\pi$ for hver enkelt enhed bliver $n/N$. Herefter kan vi danne et estimat for $t_y$ med Horvitz-Thompson estimatoren, hvor hver enkelt observation fra stikprøven vægtes med $\pi^{-1}$:
$$\hat{t}_y = \sum_{j=1}^n \frac{N}{n}y_j$$

> Nogle bryder sig ikke om at opskrive summationen for $\hat{t}_y$ med samme index $j$ som for $t_y$, da det på en måde indikerer, at summen løber over de første $n$ enheder ud af $N$. I stedet kan man betegne den udvalgte stikprøve med $\mathcal{S}$ og skrive
$$ \hat{t}_y = \sum_{j \in \mathcal{S}} \pi^{-1}y_j$$
Som regel er der dog *ikke* tvivl om hvad der menes, og derfor foretrækkes notationen med summation over $j = 1, \ldots, n$.

Variansen for $\hat{t}_y$ bestemmes ved
$$V(\hat{t}_y) = (1-\frac{n}{N}) N^2 \frac{\hat{s}^2}{n} $$
hvor $\hat{s}^2$ er et estimat for variansen i populationen $V(y) = \sigma^2$. Vi estimerer $s$ med stikprøvestandardafvigelsen. Som regel er det ikke variansen men derimod spredning på estimatet, som vi er interesserede i. Denne størrelses kaldes også for *standardfejlen* (s.e., standard error) og beregnes ved at uddrage kvadratroden af variansen.

Ønskede vi i stedet at estimere middelværdien $\mu$ i populationen, da sættes blot totalen mod populationsstørrelsen hvorved vi får
$$\hat{\mu} = \bar{y} = \frac{1}{N} \hat{t}_y = \sum_{i=1}^n \frac{1}{n}y_i $$
Variansen for den estimerede middelværdi beregnes derfor som
$$V(\bar{y}) = V(\frac{1}{N}\hat{t}_y) = \frac{1}{N^2}V(\hat{t}_y) = (1-\frac{n}{N}) \frac{\hat{s}^2}{n}$$

### Kort resumé af STSI og HT-estimatoren
Vi ser nu på tilfældet hvor populationen $U$ deles op i $L$ disjunkte mængder, det vil sige $U = U_1 \cup U_2 \cup \ldots \cup U_L$ og $U_i \cap U_j = \emptyset$ for $i \ne j$. Opdelingen kaldes en *stratifikation*, og delmængderne kaldes *strata*. Ideen er at i stedet for at trække en stikprøve simpelt tilfældigt i hele $U$, så trækker vi nu en stikprøve simpelt tilfældigt i hver af de $L$ strata. Vi ved allerede, hvordan vi beregner HT-estimat og tilhørende standardfejl for en SRS stikprøve, nu skal vi blot kombinere de $L$ estimater og standardfejl til et samlet estimat.

Først ser vi på estimation af $t_y$, hvor estimatet beregnes som summen af de stratumvise estimater
$$\hat{t}_y^{st} = \sum_{h=1}^L \hat{t}_h = \sum_{h=1}^L \sum_{j=1}^{n_h} \frac{N_h}{n_h} y_{hj}$$
hvor $y_{hj}$ er den $j$'te enhed i stikprøven i det $h$'te stratum. Da stikprøven antages trukkes uafhængigt i de to strata (STSI, stratified simpel random sampling) beregnes variansen som
$$V(\hat{t}_y^{st}) 
= V(\sum_{h=1}^L \hat{t}_h) 
= \sum_{h=1}^L V(\hat{t}_h) 
= \sum_{h=1}^L (1-\frac{n_h}{N_h}) N_h^2 \frac{\hat{s}_h^2}{n_h}$$

Hvis vi i stedet vil estimere middelværdien er det ikke helt så simpelt, da vi bliver nødt til at tage hensyn til den relative størrelse af det enkelte stratum (stratumvægten)
$$\bar{y}^{st}
= \frac{\sum_{h=1}^L N_h \bar{y}_h}{N}
= \sum_{h=1}^L \frac{N_h}{N} \bar{y}_h
= \sum_{h=1}^L W_h \bar{y}_h
$$
Dette følger blandt andet af følgende omskrivning af udtrykket for populationsgennemsnittet
$$\mu = \frac{\sum_{i=1}^N y_i}{N}
= \frac{\sum_{h=1}^L \sum_{j=1}^{N_h} y_{hj}}{N}
= \frac{\sum_{h=1}^L N_h \mu_h}{N}
= \sum_{h=1}^L W_h \mu_h$$

Dermed kan vi også opstille udtrykket for variansen af estimatet for middelværdien baseret på en stratificeret stikprøve
$$V(\bar{y}^{st})
= V(\sum_{h=1}^L W_h \bar{y}_h)
= \sum_{h=1}^L W_h^2 V(\bar{y}_h)$$

### Simpelt eksperiment med stratificeret sampling

Lad os nu forestille os, at vi deler populationen $U$ over i to halvdele, $U_1$ og $U_2$. De to halvdele kan også opfattes som *strata* selvom opdelingen er sket helt tilfældigt. De to halvdele er lige store, $N_1 = N_2 = N/2$, og da opdelingen er sket tilfældigt er middelværdi og varians af $y$ den samme i de to halvdele, det vil sige $\mu_1 = \mu_2$ og $\sigma_1^2 = \sigma_2^2$.  

Lad os også dele stikprøven over i to lige store dele, $n_1 = n_2 = n/2$. Det vil sige at i stedet for en stikprøve på $n$ ud af $N$, så har vi nu to stikprøver af den halve størrelse. Hvad er konsekvensen af dette i forhold til usikkerhed (standardfejl) på estimaterne for total og middelværdi?

Først total:
$$\begin{aligned}
V(\hat{t}_y^{st}) &= \sum_{h=1}^2 (1-\frac{n_h}{N_h}) N_h^2 \frac{\hat{s}_h^2}{n_h} \\
&= \sum_{h=1}^2 (1-\frac{\frac{1}{2}n}{\frac{1}{2}N}) (\frac{1}{2}N)^2 \frac{\hat{s}_h^2}{\frac{1}{2}n} \\
&= \sum_{h=1}^2 \frac{1}{2} (1-\frac{n}{N}) N^2 \frac{\hat{s}_h^2}{n}\\
&= (1-\frac{n}{N}) N^2 \frac{\hat{s}_h^2}{n}\\
&=V(\hat{t}_y)
\end{aligned}$$

Det vil sige, at under de nævnte forudsætninger er der intet vundet (eller tabt) ved at lave en stratifikation.

Vi kan gentage beregningen for estimatet for middelværdien:
$$\begin{aligned}
V(\bar{y}^{st}) &= \sum_{h=1}^2 W_h^2 V(\bar{y}_h) \\
&= \sum_{h=1}^2 (\frac{N_h}{N})^2 (1-\frac{n_h}{N_h}) \frac{\hat{s_h}^2}{n_h} \\
&= \sum_{h=1}^2 (\frac{\frac{1}{2}N}{N})^2 (1-\frac{\frac{1}{2}n}{\frac{1}{2}N}) \frac{\hat{s_h}^2}{\frac{1}{2}n}\\
&= \sum_{h=1}^2 \frac{1}{2} (1-\frac{n}{N}) \frac{\hat{s_h}^2}{n}\\
&= (1-\frac{n}{N}) \frac{\hat{s_h}^2}{n} \\
&= V(\bar{y})
\end{aligned}$$
Resultatet bliver naturligvis det samme.


<!-- ```{r cars} -->
<!-- summary(cars) -->
<!-- ``` -->

<!-- ## Including Plots -->

<!-- You can also embed plots, for example: -->

<!-- ```{r pressure, echo=FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot. -->
